$files = FileList.new([
	"content/colorediffs/callbacks.js",
	"content/colorediffs/colorediffs.js",
	"content/colorediffs/contents.rdf",
	"content/colorediffs/dom.js",
	"content/colorediffs/globals.js",
	"content/colorediffs/icon.png",
	"content/colorediffs/ilUtils.js",
	"content/colorediffs/main-overlay.xul",
	"content/colorediffs/msgwindowoverlay.xul",
	"content/colorediffs/overlay.js",
	"content/colorediffs/overlay.xul",
	"content/colorediffs/prefs.js",
	"content/colorediffs/toolbar.js",

	"content/colorediffs/bindings/bindings.css",
	"content/colorediffs/bindings/colorpicker.css",
	"content/colorediffs/bindings/main-bindings.xbl",

	"content/colorediffs/options/context-view-options.xul",
	"content/colorediffs/options/unified-view-options.xul",
	"content/colorediffs/options/side-by-side-view-options.xul",
	"content/colorediffs/options/options.css",
	"content/colorediffs/options/options.js",
	"content/colorediffs/options/options.xul",
	"content/colorediffs/options/options-pref.js",
	"content/colorediffs/options/options-pref-callback.js",

	"content/colorediffs/parsers/main-parser.js",
	"content/colorediffs/parsers/context-parser.js",
	"content/colorediffs/parsers/unified-parser.js",

	"content/colorediffs/transformations/composite-transformation.js",
	"content/colorediffs/transformations/composite-init.js",
	"content/colorediffs/transformations/composite-run.js",
	"content/colorediffs/transformations/make-lines-equal-length.js",
	"content/colorediffs/transformations/find-common-name.js",
	"content/colorediffs/transformations/detect-old-new-files.js",
	"content/colorediffs/transformations/select-old-new-files.js",
	"content/colorediffs/transformations/truncate-file-names.js",
	"content/colorediffs/transformations/add-title.js",
	"content/colorediffs/transformations/main-transformation.js",
	"content/colorediffs/transformations/replace-file-names-transformation.js",
	"content/colorediffs/transformations/replace-tabs.js",
	"content/colorediffs/transformations/show-whitespaces-transformation.js",
	"content/colorediffs/transformations/show-line-numbers.js",
	"content/colorediffs/transformations/collect-tab-sizes.js",
	"content/colorediffs/transformations/calc-chunk-size.js",

	"content/colorediffs/views/main-view.js",
	"content/colorediffs/views/side-by-side-view.js",
	"content/colorediffs/views/unified-view.js",
	"content/colorediffs/views/context-view.js",

	"skin/colorediffs.css",
	"skin/white-space.png",
	"skin/line-numbers.png",
	"skin/options.png"
])
