/* SPDX-License-Identifier: MPL-2.0 */

/* eslint-disable no-multi-spaces */
const FullStyleList = [
    { file: "base16/3024",                          name: "3024" },
    { file: "a11y-dark",                            name: "A11y Dark" },
    { file: "a11y-light",                           name: "A11y Light" },
    { file: "agate",                                name: "Agate" },
    { file: "an-old-hope",                          name: "An Old Hope" },
    { file: "androidstudio",                        name: "Android Studio" },
    { file: "base16/apathy",                        name: "Apathy" },
    { file: "base16/apprentice",                    name: "Apprentice" },
    { file: "arduino-light",                        name: "Arduino Light" },
    { file: "arta",                                 name: "Arta" },
    { file: "ascetic",                              name: "Ascetic" },
    { file: "base16/ashes",                         name: "Ashes" },
    { file: "base16/atelier-cave",                  name: "Atelier Cave" },
    { file: "base16/atelier-cave-light",            name: "Atelier Cave Light" },
    { file: "base16/atelier-dune",                  name: "Atelier Dune" },
    { file: "base16/atelier-dune-light",            name: "Atelier Dune Light" },
    { file: "base16/atelier-estuary",               name: "Atelier Estuary" },
    { file: "base16/atelier-estuary-light",         name: "Atelier Estuary Light" },
    { file: "base16/atelier-forest",                name: "Atelier Forest" },
    { file: "base16/atelier-forest-light",          name: "Atelier Forest Light" },
    { file: "base16/atelier-heath",                 name: "Atelier Heath" },
    { file: "base16/atelier-heath-light",           name: "Atelier Heath Light" },
    { file: "base16/atelier-lakeside",              name: "Atelier Lakeside" },
    { file: "base16/atelier-lakeside-light",        name: "Atelier Lakeside Light" },
    { file: "base16/atelier-plateau",               name: "Atelier Plateau" },
    { file: "base16/atelier-plateau-light",         name: "Atelier Plateau Light" },
    { file: "base16/atelier-savanna",               name: "Atelier Savanna" },
    { file: "base16/atelier-savanna-light",         name: "Atelier Savanna Light" },
    { file: "base16/atelier-seaside",               name: "Atelier Seaside" },
    { file: "base16/atelier-seaside-light",         name: "Atelier Seaside Light" },
    { file: "base16/atelier-sulphurpool",           name: "Atelier Sulphurpool" },
    { file: "base16/atelier-sulphurpool-light",     name: "Atelier Sulphurpool Light" },
    { file: "base16/atlas",                         name: "Atlas" },
    { file: "atom-one-dark",                        name: "Atom One Dark" },
    { file: "atom-one-dark-reasonable",             name: "Atom One Dark Reasonable" },
    { file: "atom-one-light",                       name: "Atom One Light" },
    { file: "base16/bespin",                        name: "Bespin" },
    { file: "base16/black-metal",                   name: "Black Metal" },
    { file: "base16/black-metal-bathory",           name: "Black Metal Bathory" },
    { file: "base16/black-metal-burzum",            name: "Black Metal Burzum" },
    { file: "base16/black-metal-dark-funeral",      name: "Black Metal Dark Funeral" },
    { file: "base16/black-metal-gorgoroth",         name: "Black Metal Gorgoroth" },
    { file: "base16/black-metal-immortal",          name: "Black Metal Immortal" },
    { file: "base16/black-metal-khold",             name: "Black Metal Khold" },
    { file: "base16/black-metal-marduk",            name: "Black Metal Marduk" },
    { file: "base16/black-metal-mayhem",            name: "Black Metal Mayhem" },
    { file: "base16/black-metal-nile",              name: "Black Metal Nile" },
    { file: "base16/black-metal-venom",             name: "Black Metal Venom" },
    { file: "base16/brewer",                        name: "Brewer" },
    { file: "base16/bright",                        name: "Bright" },
    { file: "base16/brogrammer",                    name: "Brogrammer" },
    { file: "brown-paper",                          name: "Brown Paper" },
    { file: "base16/brush-trees",                   name: "Brush Trees" },
    { file: "base16/brush-trees-dark",              name: "Brush Trees Dark" },
    { file: "base16/chalk",                         name: "Chalk" },
    { file: "base16/circus",                        name: "Circus" },
    { file: "base16/classic-dark",                  name: "Classic Dark" },
    { file: "base16/classic-light",                 name: "Classic Light" },
    { file: "codepen-embed",                        name: "Codepen Embed" },
    { file: "base16/codeschool",                    name: "Codeschool" },
    { file: "color-brewer",                         name: "Color Brewer" },
    { file: "base16/colors",                        name: "Colors" },
    { file: "base16/cupcake",                       name: "Cupcake" },
    { file: "base16/cupertino",                     name: "Cupertino" },
    { file: "base16/danqing",                       name: "Danqing" },
    { file: "base16/darcula",                       name: "Darcula" },
    { file: "dark",                                 name: "Dark" },
    { file: "base16/dark-violet",                   name: "Dark Violet" },
    { file: "base16/darkmoss",                      name: "Darkmoss" },
    { file: "base16/darktooth",                     name: "Darktooth" },
    { file: "base16/decaf",                         name: "Decaf" },
    { file: "default",                              name: "Default" },
    { file: "base16/default-dark",                  name: "Default Dark" },
    { file: "base16/default-light",                 name: "Default Light" },
    { file: "devibeans",                            name: "Devibeans" },
    { file: "base16/dirtysea",                      name: "Dirtysea" },
    { file: "docco",                                name: "Docco" },
    { file: "base16/dracula",                       name: "Dracula" },
    { file: "base16/edge-dark",                     name: "Edge Dark" },
    { file: "base16/edge-light",                    name: "Edge Light" },
    { file: "base16/eighties",                      name: "Eighties" },
    { file: "base16/embers",                        name: "Embers" },
    { file: "base16/equilibrium-dark",              name: "Equilibrium Dark" },
    { file: "base16/equilibrium-gray-dark",         name: "Equilibrium Gray Dark" },
    { file: "base16/equilibrium-gray-light",        name: "Equilibrium Gray Light" },
    { file: "base16/equilibrium-light",             name: "Equilibrium Light" },
    { file: "base16/espresso",                      name: "Espresso" },
    { file: "base16/eva",                           name: "Eva" },
    { file: "base16/eva-dim",                       name: "Eva Dim" },
    { file: "far",                                  name: "Far" },
    { file: "felipec",                              name: "FelipeC" },
    { file: "base16/flat",                          name: "Flat" },
    { file: "foundation",                           name: "Foundation" },
    { file: "base16/framer",                        name: "Framer" },
    { file: "base16/fruit-soda",                    name: "Fruit Soda" },
    { file: "gml",                                  name: "GML" },
    { file: "base16/gigavolt",                      name: "Gigavolt" },
    { file: "github",                               name: "GitHub" },
    { file: "base16/github",                        name: "GitHub (Base16)" },
    { file: "github-dark",                          name: "GitHub Dark" },
    { file: "github-dark-dimmed",                   name: "GitHub Dark Dimmed" },
    { file: "base16/google-dark",                   name: "Google Dark (Base16)" },
    { file: "base16/google-light",                  name: "Google Light" },
    { file: "googlecode",                           name: "Google Code" },
    { file: "gradient-dark",                        name: "Gradient Dark" },
    { file: "gradient-light",                       name: "Gradient Light" },
    { file: "grayscale",                            name: "Grayscale" },
    { file: "base16/grayscale-dark",                name: "Grayscale Dark" },
    { file: "base16/grayscale-light",               name: "Grayscale Light" },
    { file: "base16/green-screen",                  name: "Green Screen" },
    { file: "base16/gruvbox-dark-hard",             name: "Gruvbox Dark Hard" },
    { file: "base16/gruvbox-dark-pale",             name: "Gruvbox Dark Pale" },
    { file: "base16/gruvbox-dark-medium",           name: "Gruvbox Dark Medium" },
    { file: "base16/gruvbox-dark-soft",             name: "Gruvbox Dark Soft" },
    { file: "base16/gruvbox-light-hard",            name: "Gruvbox Light Hard" },
    { file: "base16/gruvbox-light-medium",          name: "Gruvbox Light Medium" },
    { file: "base16/gruvbox-light-soft",            name: "Gruvbox Light Soft" },
    { file: "base16/hardcore",                      name: "Hardcore" },
    { file: "base16/harmonic16-dark",               name: "Harmonic16 Dark" },
    { file: "base16/harmonic16-light",              name: "Harmonic16 Light" },
    { file: "base16/heetch-dark",                   name: "Heetch Dark" },
    { file: "base16/heetch-light",                  name: "Heetch Light" },
    { file: "base16/helios",                        name: "Helios" },
    { file: "base16/hopscotch",                     name: "Hopscotch" },
    { file: "base16/horizon-dark",                  name: "Horizon Dark" },
    { file: "base16/horizon-light",                 name: "Horizon Light" },
    { file: "base16/humanoid-dark",                 name: "Humanoid Dark" },
    { file: "base16/humanoid-light",                name: "Humanoid Light" },
    { file: "hybrid",                               name: "Hybrid" },
    { file: "base16/ia-dark",                       name: "iA Dark" },
    { file: "base16/ia-light",                      name: "iA Light" },
    { file: "ir-black",                             name: "IR Black" },
    { file: "base16/ir-black",                      name: "IR Black (Base16)" },
    { file: "base16/icy-dark",                      name: "Icy Dark" },
    { file: "idea",                                 name: "Idea" },
    { file: "intellij-light",                       name: "IntelliJ Light" },
    { file: "isbl-editor-dark",                     name: "ISBL Editor Dark" },
    { file: "isbl-editor-light",                    name: "ISBL Editor Light" },
    { file: "base16/isotope",                       name: "Isotope" },
    { file: "base16/kimber",                        name: "Kimber" },
    { file: "kimbie-dark",                          name: "Kimbie Dark" },
    { file: "kimbie-light",                         name: "Kimbie Light" },
    { file: "lightfair",                            name: "Lightfair" },
    { file: "lioshi",                               name: "Lioshi" },
    { file: "base16/london-tube",                   name: "London Tube" },
    { file: "base16/macintosh",                     name: "Macintosh" },
    { file: "magula",                               name: "Magula" },
    { file: "base16/marrakesh",                     name: "Marrakesh" },
    { file: "base16/materia",                       name: "Materia" },
    { file: "base16/material",                      name: "Material" },
    { file: "base16/material-darker",               name: "Material Darker" },
    { file: "base16/material-lighter",              name: "Material Lighter" },
    { file: "base16/material-palenight",            name: "Material Palenight" },
    { file: "base16/material-vivid",                name: "Material Vivid" },
    { file: "base16/mellow-purple",                 name: "Mellow Purple" },
    { file: "base16/mexico-light",                  name: "Mexico Light" },
    { file: "base16/mocha",                         name: "Mocha" },
    { file: "mono-blue",                            name: "Mono Blue" },
    { file: "monokai",                              name: "Monokai" },
    { file: "monokai-sublime",                      name: "Monokai Sublime" },
    { file: "base16/monokai",                       name: "Monokai (Base16)" },
    { file: "nnfx-dark",                            name: "NNFX Dark" },
    { file: "nnfx-light",                           name: "NNFX Light" },
    { file: "base16/nebula",                        name: "Nebula" },
    { file: "night-owl",                            name: "Night Owl" },
    { file: "nord",                                 name: "Nord" },
    { file: "base16/nord",                          name: "Nord (Base16)" },
    { file: "base16/nova",                          name: "Nova" },
    { file: "obsidian",                             name: "Obsidian" },
    { file: "base16/ocean",                         name: "Ocean" },
    { file: "base16/oceanicnext",                   name: "OceanicNext" },
    { file: "base16/one-light",                     name: "One Light" },
    { file: "base16/onedark",                       name: "OneDark" },
    { file: "base16/outrun-dark",                   name: "Outrun Dark" },
    { file: "panda-syntax-dark",                    name: "Panda Syntax Dark" },
    { file: "panda-syntax-light",                   name: "Panda Syntax Light" },
    { file: "base16/papercolor-dark",               name: "Papercolor Dark" },
    { file: "base16/papercolor-light",              name: "Papercolor Light" },
    { file: "base16/paraiso",                       name: "Paraiso" },
    { file: "paraiso-dark",                         name: "Paraiso Dark" },
    { file: "paraiso-light",                        name: "Paraiso Light" },
    { file: "base16/pasque",                        name: "Pasque" },
    { file: "base16/phd",                           name: "PhD" },
    { file: "base16/pico",                          name: "Pico" },
    { file: "pojoaque",                             name: "Pojoaque" },
    { file: "base16/pop",                           name: "Pop" },
    { file: "base16/porple",                        name: "Porple" },
    { file: "purebasic",                            name: "PureBASIC" },
    { file: "qtcreator-dark",                       name: "Qt Creator Dark" },
    { file: "qtcreator-light",                      name: "Qt Creator Light" },
    { file: "base16/qualia",                        name: "Qualia" },
    { file: "base16/railscasts",                    name: "Railscasts" },
    { file: "rainbow",                              name: "Rainbow" },
    { file: "base16/rebecca",                       name: "Rebecca" },
    { file: "base16/ros-pine",                      name: "Rosé Pine" },
    { file: "base16/ros-pine-dawn",                 name: "Rosé Pine Dawn" },
    { file: "base16/ros-pine-moon",                 name: "Rosé Pine Moon" },
    { file: "routeros",                             name: "RouterOS (MikroTik)" },
    { file: "base16/sagelight",                     name: "Sagelight" },
    { file: "base16/sandcastle",                    name: "Sandcastle" },
    { file: "school-book",                          name: "School Book" },
    { file: "base16/seti-ui",                       name: "Seti UI" },
    { file: "shades-of-purple",                     name: "Shades of Purple" },
    { file: "base16/shapeshifter",                  name: "Shapeshifter" },
    { file: "base16/silk-dark",                     name: "Silk Dark" },
    { file: "base16/silk-light",                    name: "Silk Light" },
    { file: "base16/snazzy",                        name: "Snazzy" },
    { file: "base16/solar-flare",                   name: "Solar Flare" },
    { file: "base16/solar-flare-light",             name: "Solar Flare Light" },
    { file: "base16/solarized-dark",                name: "Solarized Dark" },
    { file: "base16/solarized-light",               name: "Solarized Light" },
    { file: "base16/spacemacs",                     name: "Spacemacs" },
    { file: "srcery",                               name: "Srcery" },
    { file: "stackoverflow-dark",                   name: "Stack Overflow Dark" },
    { file: "stackoverflow-light",                  name: "Stack Overflow Light" },
    { file: "base16/summercamp",                    name: "Summercamp" },
    { file: "base16/summerfruit-dark",              name: "Summerfruit Dark" },
    { file: "base16/summerfruit-light",             name: "Summerfruit Light" },
    { file: "sunburst",                             name: "Sunburst" },
    { file: "base16/synth-midnight-terminal-dark",  name: "Synth Midnight Terminal Dark" },
    { file: "base16/synth-midnight-terminal-light", name: "Synth Midnight Terminal Light" },
    { file: "base16/tango",                         name: "Tango" },
    { file: "base16/tender",                        name: "Tender" },
    { file: "tokyo-night-dark",                     name: "Tokyo Night Dark" },
    { file: "tokyo-night-light",                    name: "Tokyo Night Light" },
    { file: "base16/tomorrow",                      name: "Tomorrow" },
    { file: "base16/tomorrow-night",                name: "Tomorrow Night" },
    { file: "tomorrow-night-blue",                  name: "Tomorrow Night Blue" },
    { file: "tomorrow-night-bright",                name: "Tomorrow Night Bright" },
    { file: "base16/twilight",                      name: "Twilight" },
    { file: "base16/unikitty-dark",                 name: "Unikitty Dark" },
    { file: "base16/unikitty-light",                name: "Unikitty Light" },
    { file: "vs",                                   name: "VisualStudio" },
    { file: "vs2015",                               name: "VisualStudio 2015 Dark" },
    { file: "base16/vulcan",                        name: "Vulcan" },
    { file: "base16/windows-10",                    name: "Windows 10" },
    { file: "base16/windows-10-light",              name: "Windows 10 Light" },
    { file: "base16/windows-95",                    name: "Windows 95" },
    { file: "base16/windows-95-light",              name: "Windows 95 Light" },
    { file: "base16/windows-high-contrast",         name: "Windows High Contrast" },
    { file: "base16/windows-high-contrast-light",   name: "Windows High Contrast Light" },
    { file: "base16/windows-nt",                    name: "Windows NT" },
    { file: "base16/windows-nt-light",              name: "Windows NT Light" },
    { file: "base16/woodland",                      name: "Woodland" },
    { file: "xcode",                                name: "XCode" },
    { file: "base16/xcode-dusk",                    name: "XCode Dusk" },
    { file: "xt256",                                name: "xt256" },
    { file: "base16/zenburn",                       name: "Zenburn" },
];
/* eslint-enable no-multi-spaces */

export { FullStyleList };
