name: ESLint

on:
  pull_request: {}
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm install --save-dev eslint standard
    - name: Run ESLint
      run: npx eslint scripts options
